
-- PRAGMA foreign_keys = ON;

-- init database in a batch 

Drop TABLE IF EXISTS 基金;
Drop TABLE IF EXISTS 历史净值;
Drop TABLE IF EXISTS 买入费率;
Drop TABLE IF EXISTS 卖出费率;
Drop TABLE IF EXISTS 交易类型;
Drop TABLE IF EXISTS 交易记录;


CREATE TABLE 基金 (
    id INTEGER NOT NULL UNIQUE,
    名称 VARCHAR(30) NOT NULL UNIQUE,
    代码 VARCHAR(6) NOT NULL UNIQUE,
    成立日期 Date NOT NULL,
    PRIMARY KEY(id)
);

-- this is comment

CREATE TABLE 历史净值 (
    基金Id INTEGER NOT NULL REFERENCES 基金(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    日期 Date NOT NULL,
    单位净值 DOUBLE NOT NULL,
    日涨幅 VARCHAR(7) NOT NULL,
    PRIMARY KEY(基金Id, 日期)
);

-- and another comments

CREATE TABLE 买入费率 (
    基金Id INTEGER NOT NULL REFERENCES 基金(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    购买金额 INTEGER NOT NULL,
    费率 VARCHAR(6) NOT NULL,
    PRIMARY KEY(基金Id, 购买金额)
);

CREATE TABLE 卖出费率 (
    基金Id INTEGER NOT NULL REFERENCES 基金(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    持有天数 INTEGER NOT NULL,
    费率 VARCHAR(6) NOT NULL,
    PRIMARY KEY(基金Id, 持有天数)
);

CREATE TABLE 交易类型 (
    id INTEGER NOT NULL UNIQUE,
    类型 VARCHAR(4) NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE 交易记录 (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    基金Id INTEGER NOT NULL REFERENCES 基金(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    日期 Date NOT NULL,
    类型 INTEGER NOT NULL REFERENCES 交易类型(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    金额 DOUBLE NOT NULL
);



